version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: seek_mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_client
      MYSQL_USER: seek
      MYSQL_PASSWORD: seek1@
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
